version: '3'
services:

  test_pg_zen_engine:
    container_name: pg_zen_engine_test
    build:
        context: ..
        dockerfile: ./dockerfiles/db/Dockerfile
    environment:
      USER: postgres
    command:
      - cargo
      - pgrx
      - test
      - pg16
